import React from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, Brain, TrendingUp, Target, BarChart3, Info } from 'lucide-react';
import SEOHead from '../components/SEOHead';

const Disclaimer: React.FC = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        duration: 0.6
      }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: { duration: 0.6, ease: "easeOut" }
    }
  };

  return (
    <>
      <SEOHead 
        title="Disclaimer - ADalign.io"
        description="Important disclaimers and limitations regarding ADalign.io's AI-powered ad analysis service."
        keywords="disclaimer, ai analysis limitations, ad analysis disclaimer"
        url="/disclaimer"
      />
      
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-orange-50/30 to-red-50/20 py-16">
        <div className="container mx-auto px-4 max-w-4xl">
          
          <motion.div 
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="text-center mb-12"
          >
            <motion.div variants={itemVariants} className="mb-6">
              <div className="inline-flex items-center gap-2 bg-orange-100 text-orange-800 px-4 py-2 rounded-full text-sm font-semibold">
                <AlertTriangle className="h-4 w-4" />
                Important Information
              </div>
            </motion.div>
            
            <motion.h1 
              variants={itemVariants}
              className="text-4xl md:text-5xl font-bold mb-4 text-gray-900"
            >
              Disclaimer
            </motion.h1>
            
            <motion.p 
              variants={itemVariants}
              className="text-xl text-gray-600 max-w-2xl mx-auto"
            >
              Last updated: October 28, 2024
            </motion.p>
          </motion.div>

          <motion.div 
            className="bg-white/80 backdrop-blur-sm rounded-2xl p-8 shadow-lg border border-gray-200"
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.3 }}
          >
            
            <div className="space-y-8">
              
              <section className="bg-orange-50 p-6 rounded-xl border border-orange-200">
                <div className="flex items-center gap-3 mb-4">
                  <AlertTriangle className="h-6 w-6 text-orange-600" />
                  <h2 className="text-2xl font-bold text-gray-900">General Disclaimer</h2>
                </div>
                <div className="space-y-4 text-gray-700">
                  <p>
                    ADalign.io provides AI-powered analysis and recommendations for advertising and marketing purposes. The information provided by our service is for <strong>informational purposes only</strong> and should not be considered as guaranteed performance indicators, professional advice, or definitive predictions of marketing success.
                  </p>
                </div>
              </section>

              <section>
                <div className="flex items-center gap-3 mb-4">
                  <Brain className="h-6 w-6 text-blue-600" />
                  <h2 className="text-2xl font-bold text-gray-900">AI Analysis Limitations</h2>
                </div>
                <div className="space-y-4 text-gray-700">
                  <p>
                    Our AI-powered analysis system has the following limitations:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li><strong>Algorithmic Nature:</strong> Results are generated by artificial intelligence algorithms and may not capture all nuances of human perception</li>
                    <li><strong>Training Data Limitations:</strong> AI models are trained on historical data and may not account for emerging trends or market changes</li>
                    <li><strong>Context Sensitivity:</strong> Analysis may not fully understand specific industry contexts, target audiences, or cultural nuances</li>
                    <li><strong>Subjective Elements:</strong> Some aspects of creative evaluation are inherently subjective and may vary between different viewers</li>
                    <li><strong>Dynamic Market Conditions:</strong> Market conditions, consumer behavior, and platform algorithms change frequently</li>
                  </ul>
                </div>
              </section>

              <section>
                <div className="flex items-center gap-3 mb-4">
                  <TrendingUp className="h-6 w-6 text-green-600" />
                  <h2 className="text-2xl font-bold text-gray-900">Performance Disclaimers</h2>
                </div>
                <div className="space-y-4 text-gray-700">
                  <p>
                    Regarding performance expectations and results:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li><strong>No Guaranteed Results:</strong> We do not guarantee specific improvements in conversion rates, click-through rates, or any other performance metrics</li>
                    <li><strong>Multiple Factors:</strong> Ad performance depends on numerous factors beyond ad-to-page congruence, including targeting, budget, competition, and market conditions</li>
                    <li><strong>Industry Variations:</strong> Results may vary significantly across different industries, markets, and audience segments</li>
                    <li><strong>Testing Required:</strong> All recommendations should be tested in your specific market context before full implementation</li>
                  </ul>
                </div>
              </section>

              <section>
                <div className="flex items-center gap-3 mb-4">
                  <Target className="h-6 w-6 text-purple-600" />
                  <h2 className="text-2xl font-bold text-gray-900">Recommendation Usage</h2>
                </div>
                <div className="space-y-4 text-gray-700">
                  <p>
                    When implementing our recommendations:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li><strong>Professional Judgment:</strong> Use your professional judgment and expertise when evaluating our suggestions</li>
                    <li><strong>A/B Testing:</strong> Always test changes against your current performance before full rollout</li>
                    <li><strong>Incremental Implementation:</strong> Consider implementing changes gradually to measure impact</li>
                    <li><strong>Industry Expertise:</strong> Consult with marketing professionals familiar with your specific industry when needed</li>
                    <li><strong>Compliance Check:</strong> Ensure all changes comply with platform policies and industry regulations</li>
                  </ul>
                </div>
              </section>

              <section>
                <div className="flex items-center gap-3 mb-4">
                  <BarChart3 className="h-6 w-6 text-indigo-600" />
                  <h2 className="text-2xl font-bold text-gray-900">Data and Accuracy</h2>
                </div>
                <div className="space-y-4 text-gray-700">
                  <p>
                    Regarding the accuracy and reliability of our analysis:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li><strong>Best Effort Basis:</strong> We provide analysis on a best-effort basis using current AI technology</li>
                    <li><strong>Continuous Improvement:</strong> Our algorithms are continuously being improved but may contain errors or biases</li>
                    <li><strong>Input Quality:</strong> Analysis quality depends on the quality and completeness of input data provided</li>
                    <li><strong>Platform Changes:</strong> Social media and advertising platforms frequently change their algorithms and best practices</li>
                  </ul>
                </div>
              </section>

              <section>
                <div className="flex items-center gap-3 mb-4">
                  <Info className="h-6 w-6 text-teal-600" />
                  <h2 className="text-2xl font-bold text-gray-900">Third-Party Integrations</h2>
                </div>
                <div className="space-y-4 text-gray-700">
                  <p>
                    Our service may integrate with third-party platforms and services:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li><strong>External Dependencies:</strong> Our service relies on third-party AI services (such as OpenAI) for analysis</li>
                    <li><strong>Platform Policies:</strong> Analysis is based on current understanding of platform policies, which may change</li>
                    <li><strong>URL Analysis:</strong> Landing page analysis is based on publicly accessible content at the time of analysis</li>
                    <li><strong>Service Availability:</strong> Third-party service interruptions may affect our analysis capabilities</li>
                  </ul>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Liability Limitations</h2>
                <div className="space-y-4 text-gray-700">
                  <p>
                    ADalign.io and its operators shall not be liable for:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Any direct, indirect, incidental, consequential, or punitive damages arising from use of our service</li>
                    <li>Lost profits, lost revenue, or lost business opportunities resulting from implementing our recommendations</li>
                    <li>Decisions made based on our analysis or recommendations</li>
                    <li>Any inaccuracies in our analysis or recommendations</li>
                  </ul>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Professional Advice</h2>
                <div className="space-y-4 text-gray-700">
                  <p>
                    ADalign.io does not provide professional marketing, legal, or financial advice. Our service is a tool to assist with analysis, but should not replace:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Professional marketing consultation</li>
                    <li>Legal review of advertising content and compliance</li>
                    <li>Financial planning for advertising spend</li>
                    <li>Industry-specific expertise and guidance</li>
                  </ul>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Updates and Changes</h2>
                <div className="space-y-4 text-gray-700">
                  <p>
                    This disclaimer may be updated from time to time to reflect changes in our service, technology, or legal requirements. We encourage users to review this disclaimer periodically.
                  </p>
                </div>
              </section>

              <section className="bg-red-50 p-6 rounded-xl border border-red-200">
                <h2 className="text-2xl font-bold text-gray-900 mb-4">Important Notice</h2>
                <div className="space-y-2 text-gray-700">
                  <p>
                    <strong>By using ADalign.io, you acknowledge that you have read, understood, and agree to this disclaimer.</strong> If you do not agree with any part of this disclaimer, please discontinue use of our service.
                  </p>
                  <p className="mt-4">
                    <strong>Questions?</strong> Contact us at <strong>support@adalign.io</strong>
                  </p>
                </div>
              </section>

            </div>
          </motion.div>
        </div>
      </div>
    </>
  );
};

export default Disclaimer;